In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [2]:
x = np.array([1])

## Q#2: Create y array with elements equal to 0.

In [3]:
y = np.array([0])

## Q#3: Add x and y arrays.

In [4]:
add_arry = x + y
print(add_arry)

[1]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [8]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

1
(1,)
1
int32


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [11]:
w = np.array([[11,12],[13,14],[15,16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [19]:
z = np.arange(1,4)
re_z = z.reshape((3,1))
re_z

array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [20]:
newArray = np.hstack((re_z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [21]:
for row in newArray:
    for item in row:
        print(item)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [24]:
newArray = newArray.transpose()
print(newArray)

[[ 1  2  3]
 [11 13 15]
 [12 14 16]]


## Q#10: Decrement all elements of "newArray" with 1.

In [25]:
newArray -= 1
newArray

array([[ 0,  1,  2],
       [10, 12, 14],
       [11, 13, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [26]:
big = newArray.max()
print(big)
small = newArray.min()
print(small)

15
0


## Q#12: Print the first row of "newArray" using indexing.

In [27]:
firstRow = newArray[0]
print(firstRow)

[0 1 2]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [28]:
numb = newArray[1,1]
print(numb)

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [43]:
numb2 = newArray[0,0]
numb3 = newArray[2,1]
print(numb2,numb3)

0 13


## Q#15: Change the shape of "newArray" to (9,1).

In [45]:
newArray = newArray.reshape((9,1))
newArray

array([[ 0],
       [ 1],
       [ 2],
       [10],
       [12],
       [14],
       [11],
       [13],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [46]:
newArray = newArray.reshape((3,2))

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉