In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [124]:
x = np.ones((3, 3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Q#2: Create y array with elements equal to 0.

In [125]:
y = np.zeros((3, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [127]:
z = np.add(x, y)
print(z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [9]:
print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)

(3, 3)
2
9
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [44]:
w = np.array(
    [
        [11, 12], 
        [13, 14],
        [15, 16]
    ])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [43]:
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [83]:
newArray = np.column_stack((z, w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [84]:
for i in newArray:
    print(i)

[ 1 11 12]
[ 2 13 14]
[ 3 15 16]


## Q#9: Reverse the columns and rows of "newArray".

In [117]:
newArray = newArray.transpose()
newArray

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [129]:
newArray -=1
newArray

array([[ 0,  1,  2],
       [10, 12, 14],
       [11, 13, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [93]:
print(newArray.min())
print(newArray.max())

0
15


## Q#12: Print the first row of "newArray" using indexing.

In [111]:
newArray[0]

array([0, 1, 2])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [119]:
print(newArray[1,1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [120]:
print(newArray[0,0])
print(newArray[2,1])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [121]:
newArray.reshape(9,1 )

array([[ 0],
       [ 1],
       [ 2],
       [10],
       [12],
       [14],
       [11],
       [13],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [122]:
newArray.reshape(3, 2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉