In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [2]:
# write your code here ^_^
x = np.array([1])

## Q#2: Create y array with elements equal to 0.

In [3]:
# write your code here ^_^
y = np.array([0])

## Q#3: Add x and y arrays.

In [4]:
# write your code here ^_^
x+y

array([1])

In [ ]:
# Q4: Print x array characteristics (e.g: dimension, shape, size, type).

In [5]:
# write your code here ^_^
print('Dimension: ',x.ndim)
print('shape: ',x.shape)
print('size: ',x.size)
print('type: ',x.dtype)

Dimension:  1
shape:  (1,)
size:  1
type:  int32


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [7]:
# write your code here ^_^
w = np.array([[11,12],
             [13,14],
             [15,16]])
w = w.reshape(3,2)


## Q#6: Create z array contains the numbers from 1 to 3.

In [8]:
# write your code here ^_^

z = np.array([1,2,3])
z = z.reshape(-1,1)


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [9]:
# write your code here ^_^

newArray = np.hstack((w,z))
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [10]:
# write your code here ^_^
for row in newArray:
    for element in row:
        print(element)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [11]:
# write your code here ^_^
newArray = newArray.transpose()
newArray

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [12]:
# write your code here ^_^
newArray = newArray - 1


## Q#11: Find smallest and biggest values in "newArray".

In [13]:
# write your code here ^_^
print(newArray)
print('smallest value : ',newArray.min())
print('biggest value : ',newArray.max())

[[10 12 14]
 [11 13 15]
 [ 0  1  2]]
smallest value :  0
biggest value :  15


## Q#12: Print the first row of "newArray" using indexing.

In [14]:
# write your code here ^_^
print(newArray[0])

[10 12 14]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [15]:
# write your code here ^_^
print(newArray[0][1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [16]:
# write your code here ^_^
print(newArray[2][0],newArray[1][1])

0 13


## Q#15: Change the shape of "newArray" to (9,1).

In [17]:
# write your code here ^_^
newArray.reshape(9,1)

array([[10],
       [12],
       [14],
       [11],
       [13],
       [15],
       [ 0],
       [ 1],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [18]:
# write your code here ^_^
newArray.reshape(3,2)


ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉