In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [2]:
x=np.ones(3)

## Q#2: Create y array with elements equal to 0.

In [3]:
y=np.zeros(3)

## Q#3: Add x and y arrays.

In [4]:
np.add(x,y)

array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [5]:
print(x.ndim)
print(x.dtype)
print(x.size)
print(x.shape)

1
float64
3
(3,)


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [6]:
w=np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [7]:
z=np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [8]:
newArray=np.column_stack((w,z)) # horizontal stacking
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [9]:
for row in newArray:
    for item in row:
        print(item)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [9]:
np.ravel(newArray)

array([11, 12,  1, 13, 14,  2, 15, 16,  3])

## Q#10: Decrement all elements of "newArray" with 1.

In [10]:
print(np.subtract(newArray,1))


[[10 11  0]
 [12 13  1]
 [14 15  2]]


## Q#11: Find smallest and biggest values in "newArray".

In [11]:
print(np.min(newArray))
print(np.max(newArray))


1
16


## Q#12: Print the first row of "newArray" using indexing.

In [12]:
newArray[0,:]

array([11, 12,  1])

In [13]:
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [14]:
newArray[0,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [15]:
# beacuse i haven't change newArray with subtract using formula newArray -= 1
# subtracts 
newArray -=1 
print(newArray[0,2])
print(newArray[1,1])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [16]:
np.reshape(newArray,(9,1))

array([[10],
       [11],
       [ 0],
       [12],
       [13],
       [ 1],
       [14],
       [15],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [18]:
# it can not change it but we can change the size 
#newArray=np.resize(newArray,(2,3))
#np.reshape(newArray,(3,2))

array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

# Well Done 🎉