In [123]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [124]:
# write your code here ^_^
x = np.array([1])
x

array([1])

## Q#2: Create y array with elements equal to 0.

In [125]:
# write your code here ^_^
y = np.array([0])

## Q#3: Add x and y arrays.

In [126]:
# write your code here ^_^
sum = x+y
#OR
sum = np.add(x,y)

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [127]:
# write your code here ^_^
print(f'x\'s dimension is {x.ndim}')
print(f'x\'s shape is {x.shape}')
print(f'x\'s size is {x.size}')
print(f'x\'s data type is {x.dtype}')

x's dimension is 1
x's shape is (1,)
x's size is 1
x's data type is int64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [128]:
# write your code here ^_^
w = np.arange(11,17).reshape(3,2)
#or
w = np.array(
    [[11,12],
     [13,14],
     [15,16]
    ])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [129]:
# write your code here ^_^
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [130]:
# write your code here ^_^
newArray = np.column_stack((w,z))
print(newArray)

[[11 12  1]
 [13 14  2]
 [15 16  3]]


## Q#8: Print all elements of "newArray" using the loop.

In [131]:
# write your code here ^_^
for i in newArray:
    for element in i:
        print(element)
print('------------------')
#or
for i in newArray.flat:
    print(i)

11
12
1
13
14
2
15
16
3
------------------
11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [132]:
# write your code here ^_^
print(newArray.transpose())

[[11 13 15]
 [12 14 16]
 [ 1  2  3]]


## Q#10: Decrement all elements of "newArray" with 1.

In [133]:
# write your code here ^_^
newArray -=1
print(newArray)

[[10 11  0]
 [12 13  1]
 [14 15  2]]


## Q#11: Find smallest and biggest values in "newArray".

In [134]:
# write your code here ^_^
print(f'Smallest value is {np.min(newArray)}')
print(f'biggest value is {np.max(newArray)}')

Smallest value is 0
biggest value is 15


## Q#12: Print the first row of "newArray" using indexing.

In [135]:
# write your code here ^_^
print(newArray[0])

[10 11  0]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [136]:
# write your code here ^_^
mask = newArray == 12
print(newArray[mask], f'its index is: {np.where(mask)}')
#or
newArray[1,0]

[12] its index is: (array([1]), array([0]))


12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [137]:
# write your code here ^_^
mask2 = (newArray == 0) | (newArray == 13)
print(newArray[mask2], f'its index is: {np.where(newArray == 0)} and {np.where(newArray == 13)}')
#or
print(newArray[0,2],newArray[1,1])

[ 0 13] its index is: (array([0]), array([2])) and (array([1]), array([1]))
0 13


## Q#15: Change the shape of "newArray" to (9,1).

In [138]:
# write your code here ^_^
newArray.shape = (9,1)
newArray

array([[10],
       [11],
       [ 0],
       [12],
       [13],
       [ 1],
       [14],
       [15],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [139]:
# write your code here ^_^
newArray.shape = (3, 2)
# it cannot be (2,3) because the number of elements in the array is 9

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉