In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [18]:
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [19]:
y = np.zeros(10)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [20]:
x + y


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [35]:
x.ndim


1

In [36]:
x.shape

(10,)

In [37]:
x.size

10

In [38]:
x.dtype

dtype('float64')

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [94]:
w = np.array([[11,12,13,14,15,16]]).reshape(3,2)
w

array([[11, 12],
       [13, 14],
       [15, 16]])

In [96]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [99]:
z=np.array([1,2,3]).reshape(3,1)
z

array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [100]:
newArray = np.hstack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [103]:
for i in newArray:
    for j in i :
        print(j)
    

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [113]:
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [114]:
newArray -= 1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [117]:
newArray.min() , newArray.max()

(0, 15)

## Q#12: Print the first row of "newArray" using indexing.

In [118]:
newArray[0]


array([ 0, 10, 11])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [119]:
newArray[0,2]

11

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [132]:
newArray[[0,1],[0,2]]

array([ 0, 13])

## Q#15: Change the shape of "newArray" to (9,1).

In [131]:
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [130]:
newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉