In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [2]:
x = np.ones(4)
x

array([1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [3]:
y = np.zeros(4)
y

array([0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [4]:
np.add(x,y)

array([1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [5]:
print('Type ', x.dtype, '\nNumber of dimensions ', x.ndim, '\nShape ', x.shape, '\nSize ', x.size)


Type  float64 
Number of dimensions  1 
Shape  (4,) 
Size  4


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [6]:
w = np.arange(11,17)
w.shape = (3,2)
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [7]:
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [8]:
newArray = np.column_stack((w, z))
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [9]:
#loop in Python
for i in newArray :
    for j in i :
        print(j)
        
#loop in NumPy
np.apply_along_axis(print, axis=1, arr=newArray)

11
12
1
13
14
2
15
16
3
[11 12  1]
[13 14  2]
[15 16  3]


array([None, None, None], dtype=object)

## Q#9: Reverse the columns and rows of "newArray".

In [10]:
np.flip(newArray)

array([[ 3, 16, 15],
       [ 2, 14, 13],
       [ 1, 12, 11]])

## Q#10: Decrement all elements of "newArray" with 1.

In [11]:
newArray -= 1
newArray

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [12]:
print(newArray.min())
print(newArray.max())

0
15


## Q#12: Print the first row of "newArray" using indexing.

In [13]:
print(newArray[0])

[10 11  0]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [14]:
print(newArray[1,0])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [15]:
print(newArray[0,2],newArray[1,1])

0 13


## Q#15: Change the shape of "newArray" to (9,1).

In [16]:
newArray.shape = (9,1)
newArray

array([[10],
       [11],
       [ 0],
       [12],
       [13],
       [ 1],
       [14],
       [15],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [17]:
newArray.shape = (3,2)
newArray

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉