In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
x = np.ones((2,2))
x

array([[1., 1.],
       [1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [4]:
y = np.zeros((2,2))
y

array([[0., 0.],
       [0., 0.]])

## Q#3: Add x and y arrays.

In [5]:
np.add(x,y)

array([[1., 1.],
       [1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [7]:
print('Dimension : ', x.ndim)
print('Shape : ', x.shape)
print('Size : ', x.size)
print('Type : ', x.dtype)

Dimension :  2
Shape :  (2, 2)
Size :  4
Type :  float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [24]:
w = np.arange(11,17).reshape(3,2)
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [12]:
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [40]:
newArray = np.column_stack((w,z))
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [41]:
for i in newArray:
    for j in i:
        print(j)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [34]:
np.transpose(newArray)

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [42]:
newArray += 1
newArray

array([[12, 13,  2],
       [14, 15,  3],
       [16, 17,  4]])

## Q#11: Find smallest and biggest values in "newArray".

In [45]:
print('Min = ',newArray.min())
print('Max = ',newArray.max())

Min =  2
Max =  17


## Q#12: Print the first row of "newArray" using indexing.

In [46]:
print(newArray[0])

[12 13  2]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [54]:
for i in range(len(newArray)):
    for j in range(len(newArray)):
        if newArray[i][j] == 12:
            print(newArray[i][j])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [58]:
for i in range(len(newArray)):
    for j in range(len(newArray)):
        if newArray[i][j] == 0 or newArray[i][j] == 13:
            print(newArray[i][j])

13


## Q#15: Change the shape of "newArray" to (9,1).

In [59]:
newArray.reshape(9,1)

array([[12],
       [13],
       [ 2],
       [14],
       [15],
       [ 3],
       [16],
       [17],
       [ 4]])

## Q#16: Change the shape of "newArray" to (3,2).

In [61]:
#The size doesn't match so we can't reshape it 

# Well Done 🎉