In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [20]:
# write your code here ^_^
x = np.array([1,1])
print(x)

[1 1]


## Q#2: Create y array with elements equal to 0.

In [3]:
# write your code here ^_^
y = np.array([0,0])
print(y)

## Q#3: Add x and y arrays.

In [21]:
# write your code here ^_^
print(np.add(x,y))

[1 1]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [22]:
# write your code here ^_^
print(f"Dimension: {x.ndim}\n"
      f"Shape: {x.shape}\n"
      f"Size: {x.size}\n"
        f"Type: {x.dtype}\n")

Dimension: 1
Shape: (2,)
Size: 2
Type: int32



## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [24]:
# write your code here ^_^
w = np.array([[11,12],[13,14],[15,16]])
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [25]:
# write your code here ^_^
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [26]:
# write your code here ^_^
newArray = np.column_stack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [27]:
# write your code here ^_^
for item in newArray:
    print(item)

[ 1 11 12]
[ 2 13 14]
[ 3 15 16]


## Q#9: Reverse the columns and rows of "newArray".

In [33]:
# write your code here ^_^
newArray = newArray.transpose()
print(newArray)

[[ 0  1  2]
 [10 12 14]
 [11 13 15]]


## Q#10: Decrement all elements of "newArray" with 1.

In [34]:
# write your code here ^_^
newArray -=1
newArray

array([[ 0,  1,  2],
       [10, 12, 14],
       [11, 13, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [35]:
# write your code here ^
print(newArray.max())
print(newArray.min())

15
0


## Q#12: Print the first row of "newArray" using indexing.

In [13]:
# write your code here ^_^
newArray[0,:]

array([0, 1, 2])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [36]:
# write your code here ^_^
newArray[1,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [39]:
# write your code here ^_^
print(newArray[0,0])
print(newArray[2,1]) 

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [40]:
# write your code here ^_^
newArray.reshape(9,1)

array([[ 0],
       [ 1],
       [ 2],
       [10],
       [12],
       [14],
       [11],
       [13],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [41]:
# write your code here ^_^
newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉