In [ ]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [17]:
# write your code here ^_^
x=np.ones(3)
x

array([1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [18]:
# write your code here ^_^
y=np.zeros(3)
y

array([0., 0., 0.])

## Q#3: Add x and y arrays.

In [19]:
# write your code here ^_^
x+y

array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [77]:
# write your code here ^_^
print('type = ', x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)
print(type(x))

type =  float64
number of dimensions =  1
shape =  (3,)
size =  3
<class 'numpy.ndarray'>


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [55]:
# write your code here ^_^
w = np.array(
    [
        [11,12],
        [13,14],
        [15,16]
    ]
)
w


array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [54]:
# write your code here ^_^
z=np.arange(1,4).reshape(3,1)
z

array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [80]:
# write your code here ^_^
newArray=np.hstack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [83]:
# write your code here ^_^
for item in newArray.flat:
    print(item)
# secend way

# for row in newArray:
#     for item in row:
#         print(item)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [59]:
# write your code here ^_^
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [88]:
# write your code here ^_^
newArray-=1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [89]:
# write your code here ^_^
print(newArray.min())
print(newArray.max())



0
15


## Q#12: Print the first row of "newArray" using indexing.

In [91]:
# write your code here ^_^
print(newArray[0])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [93]:
# write your code here ^_^
print(newArray[1,1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [99]:
# write your codprint(a[-1])
print(newArray[0,0])
print(newArray[1,2])
print(newArray[0,0],newArray[1,2])

# secend way
newArray[[0,1],[0,2]]

0
13
0 13


array([ 0, 13])

## Q#15: Change the shape of "newArray" to (9,1).

In [95]:
# write your code here ^_^
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [69]:
# write your code here ^_^
newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉