In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [30]:
x = np.ones((2, 2))
x

array([[1., 1.],
       [1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [31]:
y = np.zeros((2, 2))
y

array([[0., 0.],
       [0., 0.]])

## Q#3: Add x and y arrays.

In [32]:
# nothing change
z = x + y
z

array([[1., 1.],
       [1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [33]:
print("Shape: {}".format(x.shape))
print("Dimension: {}".format(x.ndim))
print("Type: {}".format(x.dtype))
print("Size: {}".format(x.size))

Shape: (2, 2)
Dimension: 2
Type: float64
Size: 4


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [34]:
w = np.array([[11,12],[13,14],[15,16]])
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [35]:
z = np.arange(1,4)
print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [36]:
newArray = np.column_stack((w,z))
print(newArray)

[[11 12  1]
 [13 14  2]
 [15 16  3]]


## Q#8: Print all elements of "newArray" using the loop.

In [37]:
for i in newArray:
    for j in i:
        print(j)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [38]:
newArray = newArray.transpose()
print(newArray)

[[11 13 15]
 [12 14 16]
 [ 1  2  3]]


## Q#10: Decrement all elements of "newArray" with 1.

In [39]:
newArray -= 1
newArray

array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [41]:
print(newArray.min())
print(newArray.max())

0
15


## Q#12: Print the first row of "newArray" using indexing.

In [46]:
newArray[0]

array([10, 12, 14])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [48]:
newArray[0,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [50]:
newArray[2,0],newArray[1,1]

(0, 13)

## Q#15: Change the shape of "newArray" to (9,1).

In [53]:
newArray.reshape(9,1)

array([[10],
       [12],
       [14],
       [11],
       [13],
       [15],
       [ 0],
       [ 1],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [57]:
#cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉